- name: "upgrade packages."
  become: true
  apt:
    upgrade: "yes"

- name: "install dependencies."
  become: true
  apt:
    name: ["nodejs", "npm"]
    update_cache: yes

- name: "first - Get project/backend files from circleci server to local"
  become: true
  copy:
    src: /root/project/backend/
    dest: /home/ubuntu

- name: "LS to verify the dist"
  become: true
  command: ls
  args:
    chdir: /home/ubuntu

# - name: "second - Get project/backend files from circleci server to local"
#   become: true
#   copy:
#     src: /root/project/backend/dist
#     dest: /home/ubuntu/backend/

- name: "cd to backend dir"
  command: cd /home/ubuntu/backend    

- name: "run npm install"
  command: npm install
    
- name: "run npm run build"
  command: npm run build

- name: "PM2 to run back-end server"
  become: true
  shell: |
    cd /home/ubuntu/backend 
    pm2 start npm --name backend -- start
    pm2 ls